<?php

/*
 * This file is part of forked BedrockProtocol by FemboyTeam.
 * Link: https://github.com/FemboyTeam/BedrockProtocol/
 * Copyright (C) 2014-2022 PocketMine Team <https://github.com/pmmp/BedrockProtocol>
 *
 *  ⠀⠀⣽⣿⣿⣿⣧⠀⠀⠀⠠⣤⣄⡀⠀⠀⠀⠀⣰⣿⣿⣿⣿⣿⡆⠀
 *  ⠀⢀⣿⣿⣿⣿⣿⣷⡀⠀⠀⢿⣿⣿⣦⡀⠀⣰⣿⣿⣿⣿⣿⣿⡇⠀
 *  ⠀⢸⣿⣿⣿⣿⣿⣿⡿⠄⣠⣤⣿⣿⣿⣿⣄⣿⣿⣿⣿⣿⣿⣿⡇⠀
 *  ⠀⢸⣿⣿⣿⣿⣿⣿⣤⣬⣭⣬⣬⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀
 *  ⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠇⠀
 *  ⠀⠀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠿⠿⠿⣿⣿⡿⠀⠀
 *  ⠀⠀⠸⣿⣧⠀⣴⡆⠀⠀⢸⣿⣿⣿⣿⠀⠀⢸⣿⡌⣶⣿⠟⠁⠀⠀
 *  ⠀⠀⠀⠹⡿⢸⣿⡇⠀⠀⢸⣿⣿⣿⣿⠀⠀⢈⣿⡇⢸⣯⣤⣤⠀⠀
 *  ⠀⠙⣿⣿⣇⢸⣿⣇⠀⢀⣾⡿⢿⣿⣿⣀⣀⣼⣿⡇⣸⣿⡿⠁⠀⠀
 *  ⠀⠀⢀⡟⡉⠞⢻⣿⣿⣿⣿⣶⣾⣿⣿⣿⣿⣿⠋⠘⣹⣿⡄⠀⠀⠀
 *  ⠀⠀⣼⣿⣧⣶⣿⣿⣿⣟⠻⢋⣍⣉⣋⣼⣿⣿⣿⣶⢿⣿⣿⡄⠀⠀
 *  ⠀⠀⠉⠉⠀⠙⠻⢿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⠛⠁⠀⠉⠀⠀⠀⠀
 *  ⠀⠀⠀⠀⠀⠀⠀⠠⣬⣭⣽⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀
 *  ⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⣿⣿⣿⣿⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀
 *  ⠀⠀⠀⠀⠀⠀⠀⠀⠼⢿⣿⣿⣿⣿⣿⣿⣿⣿⣧⠀⠀⠀⠀⠀⠀⠀
 *  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⣿⣿⣿⣿⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀
 *  ⠀⠀⠀⠀⠀⠀⠀⠀⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀
 *
 * BedrockProtocol is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 */

declare(strict_types=1);

namespace pocketmine\network\mcpe\protocol;

/**
 * This trait provides default implementations for all packet translators, so that you don't have to manually write
 * translators for every single packet even if you don't care about them.
 *
 * This file is automatically generated. Do not edit it manually.
 */
trait PacketTranslatorDefaultImplTrait{

	public function translateLogin(LoginPacket $packet) : ?LoginPacket{
		return $packet;
	}

	public function translatePlayStatus(PlayStatusPacket $packet) : ?PlayStatusPacket{
		return $packet;
	}

	public function translateServerToClientHandshake(ServerToClientHandshakePacket $packet) : ?ServerToClientHandshakePacket{
		return $packet;
	}

	public function translateClientToServerHandshake(ClientToServerHandshakePacket $packet) : ?ClientToServerHandshakePacket{
		return $packet;
	}

	public function translateDisconnect(DisconnectPacket $packet) : ?DisconnectPacket{
		return $packet;
	}

	public function translateResourcePacksInfo(ResourcePacksInfoPacket $packet) : ?ResourcePacksInfoPacket{
		return $packet;
	}

	public function translateResourcePackStack(ResourcePackStackPacket $packet) : ?ResourcePackStackPacket{
		return $packet;
	}

	public function translateResourcePackClientResponse(ResourcePackClientResponsePacket $packet) : ?ResourcePackClientResponsePacket{
		return $packet;
	}

	public function translateText(TextPacket $packet) : ?TextPacket{
		return $packet;
	}

	public function translateSetTime(SetTimePacket $packet) : ?SetTimePacket{
		return $packet;
	}

	public function translateStartGame(StartGamePacket $packet) : ?StartGamePacket{
		return $packet;
	}

	public function translateAddPlayer(AddPlayerPacket $packet) : ?AddPlayerPacket{
		return $packet;
	}

	public function translateAddActor(AddActorPacket $packet) : ?AddActorPacket{
		return $packet;
	}

	public function translateRemoveActor(RemoveActorPacket $packet) : ?RemoveActorPacket{
		return $packet;
	}

	public function translateAddItemActor(AddItemActorPacket $packet) : ?AddItemActorPacket{
		return $packet;
	}

	public function translateTakeItemActor(TakeItemActorPacket $packet) : ?TakeItemActorPacket{
		return $packet;
	}

	public function translateMoveActorAbsolute(MoveActorAbsolutePacket $packet) : ?MoveActorAbsolutePacket{
		return $packet;
	}

	public function translateMovePlayer(MovePlayerPacket $packet) : ?MovePlayerPacket{
		return $packet;
	}

	public function translatePassengerJump(PassengerJumpPacket $packet) : ?PassengerJumpPacket{
		return $packet;
	}

	public function translateUpdateBlock(UpdateBlockPacket $packet) : ?UpdateBlockPacket{
		return $packet;
	}

	public function translateAddPainting(AddPaintingPacket $packet) : ?AddPaintingPacket{
		return $packet;
	}

	public function translateTickSync(TickSyncPacket $packet) : ?TickSyncPacket{
		return $packet;
	}

	public function translateLevelSoundEventPacketV1(LevelSoundEventPacketV1 $packet) : ?LevelSoundEventPacketV1{
		return $packet;
	}

	public function translateLevelEvent(LevelEventPacket $packet) : ?LevelEventPacket{
		return $packet;
	}

	public function translateBlockEvent(BlockEventPacket $packet) : ?BlockEventPacket{
		return $packet;
	}

	public function translateActorEvent(ActorEventPacket $packet) : ?ActorEventPacket{
		return $packet;
	}

	public function translateMobEffect(MobEffectPacket $packet) : ?MobEffectPacket{
		return $packet;
	}

	public function translateUpdateAttributes(UpdateAttributesPacket $packet) : ?UpdateAttributesPacket{
		return $packet;
	}

	public function translateInventoryTransaction(InventoryTransactionPacket $packet) : ?InventoryTransactionPacket{
		return $packet;
	}

	public function translateMobEquipment(MobEquipmentPacket $packet) : ?MobEquipmentPacket{
		return $packet;
	}

	public function translateMobArmorEquipment(MobArmorEquipmentPacket $packet) : ?MobArmorEquipmentPacket{
		return $packet;
	}

	public function translateInteract(InteractPacket $packet) : ?InteractPacket{
		return $packet;
	}

	public function translateBlockPickRequest(BlockPickRequestPacket $packet) : ?BlockPickRequestPacket{
		return $packet;
	}

	public function translateActorPickRequest(ActorPickRequestPacket $packet) : ?ActorPickRequestPacket{
		return $packet;
	}

	public function translatePlayerAction(PlayerActionPacket $packet) : ?PlayerActionPacket{
		return $packet;
	}

	public function translateHurtArmor(HurtArmorPacket $packet) : ?HurtArmorPacket{
		return $packet;
	}

	public function translateSetActorData(SetActorDataPacket $packet) : ?SetActorDataPacket{
		return $packet;
	}

	public function translateSetActorMotion(SetActorMotionPacket $packet) : ?SetActorMotionPacket{
		return $packet;
	}

	public function translateSetActorLink(SetActorLinkPacket $packet) : ?SetActorLinkPacket{
		return $packet;
	}

	public function translateSetHealth(SetHealthPacket $packet) : ?SetHealthPacket{
		return $packet;
	}

	public function translateSetSpawnPosition(SetSpawnPositionPacket $packet) : ?SetSpawnPositionPacket{
		return $packet;
	}

	public function translateAnimate(AnimatePacket $packet) : ?AnimatePacket{
		return $packet;
	}

	public function translateRespawn(RespawnPacket $packet) : ?RespawnPacket{
		return $packet;
	}

	public function translateContainerOpen(ContainerOpenPacket $packet) : ?ContainerOpenPacket{
		return $packet;
	}

	public function translateContainerClose(ContainerClosePacket $packet) : ?ContainerClosePacket{
		return $packet;
	}

	public function translatePlayerHotbar(PlayerHotbarPacket $packet) : ?PlayerHotbarPacket{
		return $packet;
	}

	public function translateInventoryContent(InventoryContentPacket $packet) : ?InventoryContentPacket{
		return $packet;
	}

	public function translateInventorySlot(InventorySlotPacket $packet) : ?InventorySlotPacket{
		return $packet;
	}

	public function translateContainerSetData(ContainerSetDataPacket $packet) : ?ContainerSetDataPacket{
		return $packet;
	}

	public function translateCraftingData(CraftingDataPacket $packet) : ?CraftingDataPacket{
		return $packet;
	}

	public function translateCraftingEvent(CraftingEventPacket $packet) : ?CraftingEventPacket{
		return $packet;
	}

	public function translateGuiDataPickItem(GuiDataPickItemPacket $packet) : ?GuiDataPickItemPacket{
		return $packet;
	}

	public function translateBlockActorData(BlockActorDataPacket $packet) : ?BlockActorDataPacket{
		return $packet;
	}

	public function translatePlayerInput(PlayerInputPacket $packet) : ?PlayerInputPacket{
		return $packet;
	}

	public function translateLevelChunk(LevelChunkPacket $packet) : ?LevelChunkPacket{
		return $packet;
	}

	public function translateSetCommandsEnabled(SetCommandsEnabledPacket $packet) : ?SetCommandsEnabledPacket{
		return $packet;
	}

	public function translateSetDifficulty(SetDifficultyPacket $packet) : ?SetDifficultyPacket{
		return $packet;
	}

	public function translateChangeDimension(ChangeDimensionPacket $packet) : ?ChangeDimensionPacket{
		return $packet;
	}

	public function translateSetPlayerGameType(SetPlayerGameTypePacket $packet) : ?SetPlayerGameTypePacket{
		return $packet;
	}

	public function translatePlayerList(PlayerListPacket $packet) : ?PlayerListPacket{
		return $packet;
	}

	public function translateSimpleEvent(SimpleEventPacket $packet) : ?SimpleEventPacket{
		return $packet;
	}

	public function translateLegacyTelemetryEvent(LegacyTelemetryEventPacket $packet) : ?LegacyTelemetryEventPacket{
		return $packet;
	}

	public function translateSpawnExperienceOrb(SpawnExperienceOrbPacket $packet) : ?SpawnExperienceOrbPacket{
		return $packet;
	}

	public function translateClientboundMapItemData(ClientboundMapItemDataPacket $packet) : ?ClientboundMapItemDataPacket{
		return $packet;
	}

	public function translateMapInfoRequest(MapInfoRequestPacket $packet) : ?MapInfoRequestPacket{
		return $packet;
	}

	public function translateRequestChunkRadius(RequestChunkRadiusPacket $packet) : ?RequestChunkRadiusPacket{
		return $packet;
	}

	public function translateChunkRadiusUpdated(ChunkRadiusUpdatedPacket $packet) : ?ChunkRadiusUpdatedPacket{
		return $packet;
	}

	public function translateItemFrameDropItem(ItemFrameDropItemPacket $packet) : ?ItemFrameDropItemPacket{
		return $packet;
	}

	public function translateGameRulesChanged(GameRulesChangedPacket $packet) : ?GameRulesChangedPacket{
		return $packet;
	}

	public function translateCamera(CameraPacket $packet) : ?CameraPacket{
		return $packet;
	}

	public function translateBossEvent(BossEventPacket $packet) : ?BossEventPacket{
		return $packet;
	}

	public function translateShowCredits(ShowCreditsPacket $packet) : ?ShowCreditsPacket{
		return $packet;
	}

	public function translateAvailableCommands(AvailableCommandsPacket $packet) : ?AvailableCommandsPacket{
		return $packet;
	}

	public function translateCommandRequest(CommandRequestPacket $packet) : ?CommandRequestPacket{
		return $packet;
	}

	public function translateCommandBlockUpdate(CommandBlockUpdatePacket $packet) : ?CommandBlockUpdatePacket{
		return $packet;
	}

	public function translateCommandOutput(CommandOutputPacket $packet) : ?CommandOutputPacket{
		return $packet;
	}

	public function translateUpdateTrade(UpdateTradePacket $packet) : ?UpdateTradePacket{
		return $packet;
	}

	public function translateUpdateEquip(UpdateEquipPacket $packet) : ?UpdateEquipPacket{
		return $packet;
	}

	public function translateResourcePackDataInfo(ResourcePackDataInfoPacket $packet) : ?ResourcePackDataInfoPacket{
		return $packet;
	}

	public function translateResourcePackChunkData(ResourcePackChunkDataPacket $packet) : ?ResourcePackChunkDataPacket{
		return $packet;
	}

	public function translateResourcePackChunkRequest(ResourcePackChunkRequestPacket $packet) : ?ResourcePackChunkRequestPacket{
		return $packet;
	}

	public function translateTransfer(TransferPacket $packet) : ?TransferPacket{
		return $packet;
	}

	public function translatePlaySound(PlaySoundPacket $packet) : ?PlaySoundPacket{
		return $packet;
	}

	public function translateStopSound(StopSoundPacket $packet) : ?StopSoundPacket{
		return $packet;
	}

	public function translateSetTitle(SetTitlePacket $packet) : ?SetTitlePacket{
		return $packet;
	}

	public function translateAddBehaviorTree(AddBehaviorTreePacket $packet) : ?AddBehaviorTreePacket{
		return $packet;
	}

	public function translateStructureBlockUpdate(StructureBlockUpdatePacket $packet) : ?StructureBlockUpdatePacket{
		return $packet;
	}

	public function translateShowStoreOffer(ShowStoreOfferPacket $packet) : ?ShowStoreOfferPacket{
		return $packet;
	}

	public function translatePurchaseReceipt(PurchaseReceiptPacket $packet) : ?PurchaseReceiptPacket{
		return $packet;
	}

	public function translatePlayerSkin(PlayerSkinPacket $packet) : ?PlayerSkinPacket{
		return $packet;
	}

	public function translateSubClientLogin(SubClientLoginPacket $packet) : ?SubClientLoginPacket{
		return $packet;
	}

	public function translateAutomationClientConnect(AutomationClientConnectPacket $packet) : ?AutomationClientConnectPacket{
		return $packet;
	}

	public function translateSetLastHurtBy(SetLastHurtByPacket $packet) : ?SetLastHurtByPacket{
		return $packet;
	}

	public function translateBookEdit(BookEditPacket $packet) : ?BookEditPacket{
		return $packet;
	}

	public function translateNpcRequest(NpcRequestPacket $packet) : ?NpcRequestPacket{
		return $packet;
	}

	public function translatePhotoTransfer(PhotoTransferPacket $packet) : ?PhotoTransferPacket{
		return $packet;
	}

	public function translateModalFormRequest(ModalFormRequestPacket $packet) : ?ModalFormRequestPacket{
		return $packet;
	}

	public function translateModalFormResponse(ModalFormResponsePacket $packet) : ?ModalFormResponsePacket{
		return $packet;
	}

	public function translateServerSettingsRequest(ServerSettingsRequestPacket $packet) : ?ServerSettingsRequestPacket{
		return $packet;
	}

	public function translateServerSettingsResponse(ServerSettingsResponsePacket $packet) : ?ServerSettingsResponsePacket{
		return $packet;
	}

	public function translateShowProfile(ShowProfilePacket $packet) : ?ShowProfilePacket{
		return $packet;
	}

	public function translateSetDefaultGameType(SetDefaultGameTypePacket $packet) : ?SetDefaultGameTypePacket{
		return $packet;
	}

	public function translateRemoveObjective(RemoveObjectivePacket $packet) : ?RemoveObjectivePacket{
		return $packet;
	}

	public function translateSetDisplayObjective(SetDisplayObjectivePacket $packet) : ?SetDisplayObjectivePacket{
		return $packet;
	}

	public function translateSetScore(SetScorePacket $packet) : ?SetScorePacket{
		return $packet;
	}

	public function translateLabTable(LabTablePacket $packet) : ?LabTablePacket{
		return $packet;
	}

	public function translateUpdateBlockSynced(UpdateBlockSyncedPacket $packet) : ?UpdateBlockSyncedPacket{
		return $packet;
	}

	public function translateMoveActorDelta(MoveActorDeltaPacket $packet) : ?MoveActorDeltaPacket{
		return $packet;
	}

	public function translateSetScoreboardIdentity(SetScoreboardIdentityPacket $packet) : ?SetScoreboardIdentityPacket{
		return $packet;
	}

	public function translateSetLocalPlayerAsInitialized(SetLocalPlayerAsInitializedPacket $packet) : ?SetLocalPlayerAsInitializedPacket{
		return $packet;
	}

	public function translateUpdateSoftEnum(UpdateSoftEnumPacket $packet) : ?UpdateSoftEnumPacket{
		return $packet;
	}

	public function translateNetworkStackLatency(NetworkStackLatencyPacket $packet) : ?NetworkStackLatencyPacket{
		return $packet;
	}

	public function translateScriptCustomEvent(ScriptCustomEventPacket $packet) : ?ScriptCustomEventPacket{
		return $packet;
	}

	public function translateSpawnParticleEffect(SpawnParticleEffectPacket $packet) : ?SpawnParticleEffectPacket{
		return $packet;
	}

	public function translateAvailableActorIdentifiers(AvailableActorIdentifiersPacket $packet) : ?AvailableActorIdentifiersPacket{
		return $packet;
	}

	public function translateLevelSoundEventPacketV2(LevelSoundEventPacketV2 $packet) : ?LevelSoundEventPacketV2{
		return $packet;
	}

	public function translateNetworkChunkPublisherUpdate(NetworkChunkPublisherUpdatePacket $packet) : ?NetworkChunkPublisherUpdatePacket{
		return $packet;
	}

	public function translateBiomeDefinitionList(BiomeDefinitionListPacket $packet) : ?BiomeDefinitionListPacket{
		return $packet;
	}

	public function translateLevelSoundEvent(LevelSoundEventPacket $packet) : ?LevelSoundEventPacket{
		return $packet;
	}

	public function translateLevelEventGeneric(LevelEventGenericPacket $packet) : ?LevelEventGenericPacket{
		return $packet;
	}

	public function translateLecternUpdate(LecternUpdatePacket $packet) : ?LecternUpdatePacket{
		return $packet;
	}

	public function translateAddEntity(AddEntityPacket $packet) : ?AddEntityPacket{
		return $packet;
	}

	public function translateRemoveEntity(RemoveEntityPacket $packet) : ?RemoveEntityPacket{
		return $packet;
	}

	public function translateClientCacheStatus(ClientCacheStatusPacket $packet) : ?ClientCacheStatusPacket{
		return $packet;
	}

	public function translateOnScreenTextureAnimation(OnScreenTextureAnimationPacket $packet) : ?OnScreenTextureAnimationPacket{
		return $packet;
	}

	public function translateMapCreateLockedCopy(MapCreateLockedCopyPacket $packet) : ?MapCreateLockedCopyPacket{
		return $packet;
	}

	public function translateStructureTemplateDataRequest(StructureTemplateDataRequestPacket $packet) : ?StructureTemplateDataRequestPacket{
		return $packet;
	}

	public function translateStructureTemplateDataResponse(StructureTemplateDataResponsePacket $packet) : ?StructureTemplateDataResponsePacket{
		return $packet;
	}

	public function translateClientCacheBlobStatus(ClientCacheBlobStatusPacket $packet) : ?ClientCacheBlobStatusPacket{
		return $packet;
	}

	public function translateClientCacheMissResponse(ClientCacheMissResponsePacket $packet) : ?ClientCacheMissResponsePacket{
		return $packet;
	}

	public function translateEducationSettings(EducationSettingsPacket $packet) : ?EducationSettingsPacket{
		return $packet;
	}

	public function translateEmote(EmotePacket $packet) : ?EmotePacket{
		return $packet;
	}

	public function translateMultiplayerSettings(MultiplayerSettingsPacket $packet) : ?MultiplayerSettingsPacket{
		return $packet;
	}

	public function translateSettingsCommand(SettingsCommandPacket $packet) : ?SettingsCommandPacket{
		return $packet;
	}

	public function translateAnvilDamage(AnvilDamagePacket $packet) : ?AnvilDamagePacket{
		return $packet;
	}

	public function translateCompletedUsingItem(CompletedUsingItemPacket $packet) : ?CompletedUsingItemPacket{
		return $packet;
	}

	public function translateNetworkSettings(NetworkSettingsPacket $packet) : ?NetworkSettingsPacket{
		return $packet;
	}

	public function translatePlayerAuthInput(PlayerAuthInputPacket $packet) : ?PlayerAuthInputPacket{
		return $packet;
	}

	public function translateCreativeContent(CreativeContentPacket $packet) : ?CreativeContentPacket{
		return $packet;
	}

	public function translatePlayerEnchantOptions(PlayerEnchantOptionsPacket $packet) : ?PlayerEnchantOptionsPacket{
		return $packet;
	}

	public function translateItemStackRequest(ItemStackRequestPacket $packet) : ?ItemStackRequestPacket{
		return $packet;
	}

	public function translateItemStackResponse(ItemStackResponsePacket $packet) : ?ItemStackResponsePacket{
		return $packet;
	}

	public function translatePlayerArmorDamage(PlayerArmorDamagePacket $packet) : ?PlayerArmorDamagePacket{
		return $packet;
	}

	public function translateCodeBuilder(CodeBuilderPacket $packet) : ?CodeBuilderPacket{
		return $packet;
	}

	public function translateUpdatePlayerGameType(UpdatePlayerGameTypePacket $packet) : ?UpdatePlayerGameTypePacket{
		return $packet;
	}

	public function translateEmoteList(EmoteListPacket $packet) : ?EmoteListPacket{
		return $packet;
	}

	public function translatePositionTrackingDBServerBroadcast(PositionTrackingDBServerBroadcastPacket $packet) : ?PositionTrackingDBServerBroadcastPacket{
		return $packet;
	}

	public function translatePositionTrackingDBClientRequest(PositionTrackingDBClientRequestPacket $packet) : ?PositionTrackingDBClientRequestPacket{
		return $packet;
	}

	public function translateDebugInfo(DebugInfoPacket $packet) : ?DebugInfoPacket{
		return $packet;
	}

	public function translatePacketViolationWarning(PacketViolationWarningPacket $packet) : ?PacketViolationWarningPacket{
		return $packet;
	}

	public function translateMotionPredictionHints(MotionPredictionHintsPacket $packet) : ?MotionPredictionHintsPacket{
		return $packet;
	}

	public function translateAnimateEntity(AnimateEntityPacket $packet) : ?AnimateEntityPacket{
		return $packet;
	}

	public function translateCameraShake(CameraShakePacket $packet) : ?CameraShakePacket{
		return $packet;
	}

	public function translatePlayerFog(PlayerFogPacket $packet) : ?PlayerFogPacket{
		return $packet;
	}

	public function translateCorrectPlayerMovePrediction(CorrectPlayerMovePredictionPacket $packet) : ?CorrectPlayerMovePredictionPacket{
		return $packet;
	}

	public function translateItemComponent(ItemComponentPacket $packet) : ?ItemComponentPacket{
		return $packet;
	}

	public function translateFilterText(FilterTextPacket $packet) : ?FilterTextPacket{
		return $packet;
	}

	public function translateClientboundDebugRenderer(ClientboundDebugRendererPacket $packet) : ?ClientboundDebugRendererPacket{
		return $packet;
	}

	public function translateSyncActorProperty(SyncActorPropertyPacket $packet) : ?SyncActorPropertyPacket{
		return $packet;
	}

	public function translateAddVolumeEntity(AddVolumeEntityPacket $packet) : ?AddVolumeEntityPacket{
		return $packet;
	}

	public function translateRemoveVolumeEntity(RemoveVolumeEntityPacket $packet) : ?RemoveVolumeEntityPacket{
		return $packet;
	}

	public function translateSimulationType(SimulationTypePacket $packet) : ?SimulationTypePacket{
		return $packet;
	}

	public function translateNpcDialogue(NpcDialoguePacket $packet) : ?NpcDialoguePacket{
		return $packet;
	}

	public function translateEduUriResource(EduUriResourcePacket $packet) : ?EduUriResourcePacket{
		return $packet;
	}

	public function translateCreatePhoto(CreatePhotoPacket $packet) : ?CreatePhotoPacket{
		return $packet;
	}

	public function translateUpdateSubChunkBlocks(UpdateSubChunkBlocksPacket $packet) : ?UpdateSubChunkBlocksPacket{
		return $packet;
	}

	public function translateSubChunk(SubChunkPacket $packet) : ?SubChunkPacket{
		return $packet;
	}

	public function translateSubChunkRequest(SubChunkRequestPacket $packet) : ?SubChunkRequestPacket{
		return $packet;
	}

	public function translatePlayerStartItemCooldown(PlayerStartItemCooldownPacket $packet) : ?PlayerStartItemCooldownPacket{
		return $packet;
	}

	public function translateScriptMessage(ScriptMessagePacket $packet) : ?ScriptMessagePacket{
		return $packet;
	}

	public function translateCodeBuilderSource(CodeBuilderSourcePacket $packet) : ?CodeBuilderSourcePacket{
		return $packet;
	}

	public function translateTickingAreasLoadStatus(TickingAreasLoadStatusPacket $packet) : ?TickingAreasLoadStatusPacket{
		return $packet;
	}

	public function translateDimensionData(DimensionDataPacket $packet) : ?DimensionDataPacket{
		return $packet;
	}

	public function translateAgentActionEvent(AgentActionEventPacket $packet) : ?AgentActionEventPacket{
		return $packet;
	}

	public function translateChangeMobProperty(ChangeMobPropertyPacket $packet) : ?ChangeMobPropertyPacket{
		return $packet;
	}

	public function translateLessonProgress(LessonProgressPacket $packet) : ?LessonProgressPacket{
		return $packet;
	}

	public function translateRequestAbility(RequestAbilityPacket $packet) : ?RequestAbilityPacket{
		return $packet;
	}

	public function translateRequestPermissions(RequestPermissionsPacket $packet) : ?RequestPermissionsPacket{
		return $packet;
	}

	public function translateToastRequest(ToastRequestPacket $packet) : ?ToastRequestPacket{
		return $packet;
	}

	public function translateUpdateAbilities(UpdateAbilitiesPacket $packet) : ?UpdateAbilitiesPacket{
		return $packet;
	}

	public function translateUpdateAdventureSettings(UpdateAdventureSettingsPacket $packet) : ?UpdateAdventureSettingsPacket{
		return $packet;
	}

	public function translateDeathInfo(DeathInfoPacket $packet) : ?DeathInfoPacket{
		return $packet;
	}

	public function translateEditorNetwork(EditorNetworkPacket $packet) : ?EditorNetworkPacket{
		return $packet;
	}

	public function translateFeatureRegistry(FeatureRegistryPacket $packet) : ?FeatureRegistryPacket{
		return $packet;
	}

	public function translateServerStats(ServerStatsPacket $packet) : ?ServerStatsPacket{
		return $packet;
	}

	public function translateRequestNetworkSettings(RequestNetworkSettingsPacket $packet) : ?RequestNetworkSettingsPacket{
		return $packet;
	}

	public function translateGameTestRequest(GameTestRequestPacket $packet) : ?GameTestRequestPacket{
		return $packet;
	}

	public function translateGameTestResults(GameTestResultsPacket $packet) : ?GameTestResultsPacket{
		return $packet;
	}

	public function translateUpdateClientInputLocks(UpdateClientInputLocksPacket $packet) : ?UpdateClientInputLocksPacket{
		return $packet;
	}

	public function translateClientCheatAbility(ClientCheatAbilityPacket $packet) : ?ClientCheatAbilityPacket{
		return $packet;
	}

	public function translateCameraPresets(CameraPresetsPacket $packet) : ?CameraPresetsPacket{
		return $packet;
	}

	public function translateUnlockedRecipes(UnlockedRecipesPacket $packet) : ?UnlockedRecipesPacket{
		return $packet;
	}

	public function translateCameraInstruction(CameraInstructionPacket $packet) : ?CameraInstructionPacket{
		return $packet;
	}

	public function translateCompressedBiomeDefinitionList(CompressedBiomeDefinitionListPacket $packet) : ?CompressedBiomeDefinitionListPacket{
		return $packet;
	}

	public function translateTrimData(TrimDataPacket $packet) : ?TrimDataPacket{
		return $packet;
	}

	public function translateOpenSign(OpenSignPacket $packet) : ?OpenSignPacket{
		return $packet;
	}

	public function translateAgentAnimation(AgentAnimationPacket $packet) : ?AgentAnimationPacket{
		return $packet;
	}

	public function translateRefreshEntitlements(RefreshEntitlementsPacket $packet) : ?RefreshEntitlementsPacket{
		return $packet;
	}

	public function translatePlayerToggleCrafterSlotRequest(PlayerToggleCrafterSlotRequestPacket $packet) : ?PlayerToggleCrafterSlotRequestPacket{
		return $packet;
	}

	public function translateSetPlayerInventoryOptions(SetPlayerInventoryOptionsPacket $packet) : ?SetPlayerInventoryOptionsPacket{
		return $packet;
	}
}
